<a href="https://colab.research.google.com/github/weasel-codes/anomaly-detection-iot/blob/main/anomaly_detection_preprocess2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import os
import pandas as pd
import numpy as np
import glob

In [17]:
base_url = '/content/drive/MyDrive/ML/anomaly/'
data_file = 'dataset.csv'

In [18]:
df = pd.read_csv(base_url+data_file)
if df.shape[1] > 8 :
  df = df.drop(columns=df.columns[0])

df = df[:5000]

df

frame.number  frame.time_relative  ...                frame.protocols  label
0            88211            70.949809  ...           eth:ethertype:ip:tcp      0
1            58708           132.842376  ...           eth:ethertype:ip:tcp      0
2           131894           296.013317  ...           eth:ethertype:ip:tcp      0
3           252744            49.393385  ...      eth:ethertype:ip:udp:data      1
4            35069            66.823389  ...           eth:ethertype:ip:tcp      0
...            ...                  ...  ...                            ...    ...
4995         23225           208.464741  ...           eth:ethertype:ip:tcp      0
4996        100953           117.434516  ...  eth:ethertype:ip:udp:udt:data      0
4997         58647           118.339898  ...      eth:ethertype:ip:udp:data      1
4998         98341           211.286852  ...  eth:ethertype:ip:udp:udt:data      0
4999        288533            73.427971  ...      eth:ethertype:ip:udp:data      1

[5000 rows x 8 columns]

In [19]:
df.isna().sum()

frame.number              0
frame.time_relative       0
frame.len                 0
data.len               2629
ip.src                   20
ip.dst                   20
frame.protocols           0
label                     0
dtype: int64

In [20]:
df['data.len'] = df['data.len'].fillna(0)
df['ip.src'] = df['ip.src'].fillna(method='ffill')
df['ip.dst'] = df['ip.dst'].fillna(method='ffill')
df.isna().sum()

frame.number           0
frame.time_relative    0
frame.len              0
data.len               0
ip.src                 0
ip.dst                 0
frame.protocols        0
label                  0
dtype: int64

In [21]:
df

frame.number  frame.time_relative  ...                frame.protocols  label
0            88211            70.949809  ...           eth:ethertype:ip:tcp      0
1            58708           132.842376  ...           eth:ethertype:ip:tcp      0
2           131894           296.013317  ...           eth:ethertype:ip:tcp      0
3           252744            49.393385  ...      eth:ethertype:ip:udp:data      1
4            35069            66.823389  ...           eth:ethertype:ip:tcp      0
...            ...                  ...  ...                            ...    ...
4995         23225           208.464741  ...           eth:ethertype:ip:tcp      0
4996        100953           117.434516  ...  eth:ethertype:ip:udp:udt:data      0
4997         58647           118.339898  ...      eth:ethertype:ip:udp:data      1
4998         98341           211.286852  ...  eth:ethertype:ip:udp:udt:data      0
4999        288533            73.427971  ...      eth:ethertype:ip:udp:data      1

[5000 rows x 8 columns]

In [22]:
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
df['ip.src']= label_encoder.fit_transform(df['ip.src'])
df['ip.dst']= label_encoder.fit_transform(df['ip.dst'])
df[:5]

frame.number  frame.time_relative  ...            frame.protocols  label
0         88211            70.949809  ...       eth:ethertype:ip:tcp      0
1         58708           132.842376  ...       eth:ethertype:ip:tcp      0
2        131894           296.013317  ...       eth:ethertype:ip:tcp      0
3        252744            49.393385  ...  eth:ethertype:ip:udp:data      1
4         35069            66.823389  ...       eth:ethertype:ip:tcp      0

[5 rows x 8 columns]

In [23]:
# Create Entites using indexes of csv
X = df.iloc[:, :-1].values #All the rows + all the columns except last
Y = df.iloc[:,-1] #Dependent vairables is last column
X.shape, Y.shape

((5000, 7), (5000,))

In [24]:
for i in range(X.shape[0]):
  var = X[i][6].split(':')
  print(var)
  temp = ""
  if len(var) == 1 :
    temp = ""
  elif len(var) == 2 :
    temp = temp + var[0] + ":" + var[1]
  elif len(var) == 3 :
    temp = temp + var[0] + ":" + var[1] + ":" + var[2]
  else :
    temp = temp + var[0] + ":" + var[1] + ":" + var[2] + ":" + var[3]

  X[i][6] = temp
  print(i , " : ", X[i][6])

Streaming output truncated to the last 5000 lines.
['eth', 'ethertype', 'ip', 'udp', 'data']
2500  :  eth:ethertype:ip:udp
['eth', 'ethertype', 'ip', 'tcp', 'data']
2501  :  eth:ethertype:ip:tcp
['eth', 'ethertype', 'ip', 'udp', 'data']
2502  :  eth:ethertype:ip:udp
['eth', 'ethertype', 'ip', 'tcp']
2503  :  eth:ethertype:ip:tcp
['eth', 'ethertype', 'ip', 'tcp']
2504  :  eth:ethertype:ip:tcp
['eth', 'ethertype', 'ip', 'udp', 'data']
2505  :  eth:ethertype:ip:udp
['eth', 'ethertype', 'ip', 'tcp']
2506  :  eth:ethertype:ip:tcp
['eth', 'ethertype', 'ip', 'udp', 'data']
2507  :  eth:ethertype:ip:udp
['eth', 'ethertype', 'ip', 'udp', 'data']
2508  :  eth:ethertype:ip:udp
['eth', 'ethertype', 'ip', 'icmp', 'ip', 'tcp']
2509  :  eth:ethertype:ip:icmp
['eth', 'ethertype', 'ip', 'tcp']
2510  :  eth:ethertype:ip:tcp
['eth', 'ethertype', 'ip', 'tcp', 'data']
2511  :  eth:ethertype:ip:tcp
['eth', 'ethertype', 'ip', 'tcp', 'ssl']
2512  :  eth:ethertype:ip:tcp
['eth', 'ethertype', 'ip', 'tcp']
2513 

In [25]:
df = pd.DataFrame(data=X)
df[6]= label_encoder.fit_transform(df[6])
df

0        1     2     3    4    5  6
0      88211  70.9498  1514     0    6  102  5
1      58708  132.842    54     0  109   92  5
2     131894  296.013    66     0  108   97  5
3     252744  49.3934    74    32  111  105  6
4      35069  66.8234  1502     0  105  100  5
...      ...      ...   ...   ...  ...  ... ..
4995   23225  208.465   114     0  108   97  5
4996  100953  117.435   992   934  105   86  6
4997   58647   118.34    60    18  105  105  6
4998   98341  211.287  1472  1414  105  100  6
4999  288533   73.428    74    32  105  105  6

[5000 rows x 7 columns]

In [26]:
X = df.iloc[:, 1:].values #All the rows + all the columns except first data frame num
X

array([[70.949809, 1514, 0.0, 6, 102, 5],
       [132.842376, 54, 0.0, 109, 92, 5],
       [296.013317, 66, 0.0, 108, 97, 5],
       ...,
       [118.339898, 60, 18.0, 105, 105, 6],
       [211.286852, 1472, 1414.0, 105, 100, 6],
       [73.427971, 74, 32.0, 105, 105, 6]], dtype=object)

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[:,[0,1,2]] = sc.fit_transform(X[:,[0,1,2]])
X

array([[-0.33562027954591445, 1.707793785637857, -0.3678133628253895, 6,
        102, 5],
       [0.5207364300771178, -0.6760344096178806, -0.3678133628253895,
        109, 92, 5],
       [2.7783989720242612, -0.6564413011637239, -0.3678133628253895,
        108, 97, 5],
       ...,
       [0.32007753122323096, -0.6662378553908023, -0.3226409496452113,
        105, 105, 6],
       [1.6061083351632799, 1.6392179060483083, 3.180730650328615, 105,
        100, 6],
       [-0.3013319835663208, -0.6433792288609527, -0.28750685050507263,
        105, 105, 6]], dtype=object)

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1) #80:20 :: Train:Test

print("Train set for X : \n", X_train)
print("\n\nTest set for X : \n", X_test)
print("\n\nTrain set for Y : \n", Y_train)
print("\n\nTest set for Y : \n", Y_test)

Train set for X : 
 [[1.2084395670940018 -0.6662378553908023 -0.3226409496452113 111 105 6]
 [1.3590825424343034 -0.5715378311957113 -0.3678133628253895 107 97 3]
 [-0.7802444772509738 -0.6433792288609527 -0.28750685050507263 111 105 6]
 ...
 [1.1245422558241205 1.6392179060483083 3.180730650328615 105 100 6]
 [0.6238271383128297 -0.5356171323630906 -0.3678133628253895 105 100 5]
 [-0.2458573964067893 -0.6433792288609527 -0.28750685050507263 111 105 6]]


Test set for X : 
 [[-0.8540317054899667 -0.6433792288609527 -0.28750685050507263 105 105 6]
 [-0.4873859640556213 -0.6433792288609527 -0.28750685050507263 105 105 6]
 [-0.5705584946984497 -0.6433792288609527 -0.28750685050507263 111 105 6]
 ...
 [0.7405106483320059 1.6392179060483083 3.180730650328615 105 86 6]
 [-0.83601609952689 -0.6433792288609527 -0.28750685050507263 111 105 6]
 [0.3068982928657375 -0.6662378553908023 -0.3226409496452113 111 105 6]]


Train set for Y : 
 1233    1
1056    0
1686    1
187     0
3840    1
       ..

In [29]:
import matplotlib.pyplot as plt
%matplotlib inline

In [32]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, max_iter=1000)
classifier.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
Y_pred = classifier.predict(X_test)
np.concatenate((Y_pred.reshape(len(Y_pred),1), np.array(Y_test).reshape(len(np.array(Y_test)),1)),1)

array([[1, 1],
       [1, 1],
       [1, 1],
       ...,
       [0, 0],
       [1, 1],
       [1, 1]])

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
Y_true = np.array(Y_test)
cm = confusion_matrix(Y_true, Y_pred) ##correct bought, incorrect bought, corerct not bought, incorrect not bought
cm

array([[500,  40],
       [119, 341]])

In [35]:
accuracy_score(Y_true, Y_pred)

0.841